### ISSUE TITLE
No stair stepping on slopes when CollisionShape3D is offset.

### ISSUE THREAD

**Issue by jacob-herrera** [DinkeyKing/Improved-KCC#5]
Issue:
When the CollisionShape3D's transform position is offset (not Vector3.ZERO) from the CharacterBody the IKCC stair stepping logic fails for sloped surfaces. This happens specifically for cylinders and capsule shapes.

Environment:
Improved-KCC: 25073ee
godot-jolt: 0.13.0-stable
Godot: 4.3-stable_win64
OS: Windows 11

Example:
[ikcc_no_sloped_step_issue.zip](https://github.com/user-attachments/files/17063635/ikcc_no_sloped_step_issue.zip) **Godot Jolt is not included with the example project because of file size limits.**

https://github.com/user-attachments/assets/8b055e93-66eb-4218-b841-966759ebb106

**Comment by DinkeyKing** [comment]
Thanks for reporting this and providing an example project! Will look into this soon.
