### ISSUE TITLE
The property `is_on_floor` returning true for the first frame after leaving the floor.

### ISSUE THREAD

**Issue by jacob-herrera** [DinkeyKing/Improved-KCC#6]
**Issue:**
When the IKCC is horizontally stationary, the character's inital jumps will report "is_on_floor = true" for the frame after jumping then all subsequent frames will accurately return "is_on_floor = false" Though, when moving horizontally, `is_on_floor` seems to always inaccurately return true for the frame after leaving the floor.

**Environment:**
Improved-KCC: 4eaf87e
godot-jolt: 0.13.0-stable
Godot: 4.3-stable_win64
OS: Windows 11

**Steps to reproduce:**

A simple print logging in the provided demo project will show these results. By adding these print statements to `example_grounded_player_controller.gd`
```
func _physics_process(p_delta_t : float) -> void :
	delta_t = p_delta_t  # Set global physics frame time
	set_initial_velocity()
	move_and_slide()
	print(is_on_floor)

...

	if is_on_floor and  Input.is_action_just_pressed("jump") :
		velocity += jump_impulse_length * up_direction
		print("JUMP")
```

The output shows that `is_on_floor` is true *after* `move_and_slide()` is called, when it should be false because the character should be in the air.
```
...
true
true
JUMP
true
false
false
...
```

**Example Project:**
[ikcc_is_on_floor_issue.zip](https://github.com/user-attachments/files/17183505/ikcc_is_on_floor_issue.zip) **(Godot Jolt is not included with the example project because of file size limits)**
The left represents the IKCC and the right represents the default CharacterBody3D. The squares represents the state of `is_on_floor` for 3 sequential frames. Green means `is_on_floor` is true, red means `is_on_floor` is false. The first square is the frame of pressing jump. The second square represents the frame after pressing jump, and the third square is 2 frames after.

https://github.com/user-attachments/assets/90c4108b-01ff-4d63-be07-9f2564508895

From my own testing, it doesn't seem like floor snapping or stair stepping is causing this.
A work around I'm using for now is: to use the CharacterBody3D's `is_on_floor()` function instead of IKCC's `is_on_floor` property.

**Comment by DinkeyKing** [comment]
Thanks for bringing this to my attention!

What casuses this, is that I do a physics query to get all the intersecting bodies before moving the character body, and then register the reported intersections as collisions.
https://github.com/DinkeyKing/Improved-KCC/blob/9d93eacffa74720010429d906d36e3b708955b9e/IKCC/ikcc.gd#L487-L492
This is used for getting the collisions that are not the result of character motion. This is needed, so that the character body can react to moving objects that collided with it.

Registering the floor collisions here is not always desirable though, so I need to make some changes here.

**Comment by DinkeyKing** [comment]
I've noticed walls can also be a problem when trying to step on a moving platform, since the wall collision can be registered before the slide collision. I suspect #4 is also caused by an unwanted collision report.

**Comment by jjj4cob** [comment]
Is there any side effect of changing the `p_set_floor` argument here to false? ~~This seems to fix the issue for me.~~
Edit: I suppose it becomes required to apply a gravity force every frame while grounded before calling `move_and_slide` to maintain grounded, though that's not a big deal for me.
https://github.com/DinkeyKing/Improved-KCC/blob/9d93eacffa74720010429d906d36e3b708955b9e/IKCC/ikcc.gd#L492

**Comment by DinkeyKing** [comment]
The only side effect of that is that when the character is moving upwards and a moving platform collides with the character from below, the character doesn't register the floor collision, so it remains in airborne state. This problem is not adressed in the built in ```move_and_slide```.

**Comment by DinkeyKing** [comment]
The `is_on_floor` property should now work as intended. The floor status should now only be updated by the motionless collision check when needed.

**Comment by jjj4cob** [comment]
Work's great. Thank you.
